services:
  postgres:
    image: postgres:latest
    container_name: postgres_inventory
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root123
      POSTGRES_DB: inventory_service
    ports:
      - "5430:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
